### ISSUE TITLE
Address in use

### ISSUE THREAD

**Issue by WaldemarStanislawski** [dbuezas/ha-addons#1]
Hello, i have problem starting this addon:

` Add-on: A9 Camera fake server
 A9 Cam fake server
-----------------------------------------------------------
 Add-on version: 2.4
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.5.3
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init: starting
s6-rc: info: service init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
-------- A9 V720 fake-server starting. --------
Stream: http://127.0.0.1:80/dev/None/stream
Snapshot: http://127.0.0.1:80/dev/None/snapshot
IrLed: http://127.0.0.1:80/dev/None/cmd?code=202&IrLed=1
Flip: http://127.0.0.1:80/dev/None/cmd?code=216&mirrorFlip=4
Exception in thread HTTP-SRV:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/a9-v720/src/v720_http.py", line 57, in serve_forever
    with ThreadingHTTPServer(("", _http_port), v720_http) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib/python3.11/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.11/socketserver.py", line 472, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address in use`

**Comment by dbuezas** [comment]
You most likely have another add-on running on port 80. I didn't make this configurable because the cameras will try to access port 80 anyway so this is afaik not an option.

Unfortunately the only options you have are:
* run the server on another device
* change the port of the other add-on
* check if your router can forward a another ip to you home assistant computer and also change relay to a different port (I don't know if this is possible)

**Comment by intx82** [comment]
@WaldemarStanislawski Try to use `--proxy-port` argument in the original server and configure proxying on yours local server (which is use 80 port)

More details you may found in: https://github.com/intx82/a9-v720/issues/15
