### ISSUE TITLE
Camera doesnt want to connect

### ISSUE THREAD

**Issue by noobnarski** [dbuezas/ha-addons#6]
I have set everything up, but the camera just doesnt connect the server for whaterver reason.
The request gets redirected according to AdGuard, but it doesnt stop blinking and there is nothing except this showing up:
A9 server
Server: connected
What could I be doing wrong?

**Comment by noobnarski** [comment]
So, as it turns out, my router (fritzbox) is somehow not relaying the dns properly, but only for the DNS rewrite.
I have no clue why.

But now it only streams once, if I close the streaming window and open it again, nothing happens.
This is the log output:

`2024-01-04 22:41:49,141  [WARNING] [HTTP] Live video request @ 0800c0000712 (172.30.32.2)
2024-01-04 22:41:49,142  [WARNING] [V720-STA@7f7f665c10] Maybe close: Clients still conected: 0
----------------------------------------
Exception occurred during processing of request from ('192.168.178.38', 7273)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/a9-v720/src/v720_http.py", line 86, in __init__
    BaseHTTPRequestHandler.__init__(
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/usr/lib/python3.11/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/lib/python3.11/http/server.py", line 424, in handle_one_request
    method()
  File "/usr/local/a9-v720/src/v720_http.py", line 368, in do_GET
    self._dev_hnds[_cmd](_dev)
  File "/usr/local/a9-v720/src/v720_http.py", line 256, in __live_hnd
    self.end_headers()
  File "/usr/lib/python3.11/http/server.py", line 538, in end_headers
    self.flush_headers()
  File "/usr/lib/python3.11/http/server.py", line 542, in flush_headers
    self.wfile.write(b"".join(self._headers_buffer))
  File "/usr/lib/python3.11/socketserver.py", line 834, in write
    self._sock.sendall(b)
OSError: [Errno 9] Bad file descriptor
----------------------------------------
2024-01-04 22:41:49,455  [WARNING] [HTTP] Host: homeassistant.local
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Referer: http://homeassistant.local:8123/
Accept-Encoding: gzip, deflate
Accept-Language: de,de-DE;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Cookie: meye_username=admin; meye_password_hash=da39a3ee5e6b4b0d3255bfef95601890afd80709


2024-01-04 22:41:49,462  [WARNING] [HTTP] Live video request @ 0800c0000712 (192.168.178.38)
2024-01-04 22:41:50,188  [WARNING] [V720-STA@7f7f665c10] Video streaming has been stopped
2024-01-04 22:41:51,151  [WARNING] [V720-STA@7f7f665c10] {
    "code": 301,
    "target": "00112233445566778899aabbccddeeff",
    "content": {
        "udpPlayBack": 1,
        "devPower": 64,
        "code": 4,
        "sdDevStatus": 0,
        "IrLed": 0,
        "instLed": 1,
        "speedGrade": 1,
        "mirrorFlip": 0,
        "sdMoveMode": 0,
        "wifiName": "SpecialConnection",
        "version": "202305301050"
    }
}
2024-01-04 22:41:51,157  [WARNING] [V720-STA@7f7f665c10] Starting video streaming
2024-01-04 22:41:52,196  [WARNING] [V720-STA@7f7f665c10] {
    "code": 301,
    "target": "00112233445566778899aabbccddeeff",
    "content": {
        "udpPlayBack": 1,
        "devPower": 64,
        "code": 4,
        "sdDevStatus": 0,
        "IrLed": 0,
        "instLed": 1,
        "speedGrade": 1,
        "mirrorFlip": 0,
        "sdMoveMode": 0,
        "wifiName": "SpecialConnection",
        "version": "202305301050"
    }
}
2024-01-04 22:41:52,201  [WARNING] [V720-STA@7f7f665c10] Starting video streaming
2024-01-04 22:41:54,463  [  ERROR] [HTTP] Camera request timeout 0800c0000712@192.168.178.173:4479
2024-01-04 22:41:59,464  [  ERROR] [HTTP] Camera request timeout 0800c0000712@192.168.178.173:4479
2024-01-04 22:42:00,692  [WARNING] [V720-STA@7f7f665c10] {
    "code": 301,
    "target": "00112233445566778899aabbccddeeff",
    "content": {
        "udpPlayBack": 1,
        "devPower": 63,
        "code": 4,
        "sdDevStatus": 0,
        "IrLed": 0,
        "instLed": 1,
        "speedGrade": 1,
        "mirrorFlip": 0,
        "sdMoveMode": 0,
        "wifiName": "SpecialConnection",
        "version": "202305301050"
    }
}
2024-01-04 22:42:00,696  [WARNING] [V720-STA@7f7f665c10] Starting video streaming`

**Comment by dbuezas** [comment]
"Bad file descriptor" may indicate an issue creating the fifo queue file. What os do you use?
