### ISSUE TITLE
After a while "freeze image"

### ISSUE THREAD

**Issue by VINCE-HA** [dbuezas/ha-addons#7]
Exception in thread UDP-CON@xxx.xxx.xxx.xxx:46832:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/a9-v720/src/v720_sta.py", line 156, in __udp_hnd
    self.__on_udp_rcv(self._udp.recv())
  File "/usr/local/a9-v720/src/v720_sta.py", line 163, in __on_udp_rcv
frame= 3622 fps=7.5 q=-1.0 size=   92042kB time=00:08:06.21 bitrate=1550.8kbits/s speed=   1x    
    self._raw_hnd_lst[f'{req.cmd}'](self._udp, data)frame= 7226 fps=7.0 q=-1.0 size=  105938kB time=00:17:07.17 bitrate= 844.9kbits/s speed=   1x    
  File "/usr/local/a9-v720/src/v720_sta.py", line 382, in __on_mjpg_rcv_hnd
    cb(self, self._vframe)
  File "/usr/local/a9-v720/src/v720_http.py", line 195, in _on_video_frame
2024-01-30 15:21:04,052  [  ERROR] [HTTP] ffmpeg output timeout 0800c0086582@xxx.xxx.xxx.xxx:58474
    video_queue.put_nowait(frame)frame=  158 fps=0.2 q=-1.0 size=    4513kB time=00:02:59.80 bitrate= 205.6kbits/s speed=0.259x    
  File "/usr/lib/python3.11/queue.py", line 191, in put_nowait
    return self.put(item, block=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/queue.py", line 137, in put
    raise Full
queue.Full

**Comment by dbuezas** [comment]
I think this means that the connection with the camera died. I found these cameras to be too unreliable so I'm not using them anymore. If you or anyone wants to add a reconnection mechanism I'd welcome a PR :)

**Comment by VINCE-HA** [comment]
Thanks 🙂
